### PR TITLE
upstream fixes

### PR DESCRIPTION
**Pull request by mb706**

### CODE REVIEW

**Comment by sumny** [comment]
I pushed some changes that incorporate a fix at a later point, because only the boston housing part was problematic with featureunion.

**Comment by mllg** [comment]
Can we silence the logger for gallery posts?

**Comment by sumny** [comment]
> Can we silence the logger for gallery posts?

sure, I think this used to be fine but you now have to set the logger threshold for bbotk instead of mlr3tuning. I fixed this in the posts where this was needed and also checked the others to set the threshold to "warn", also for the mlr3 logger

**Comment by mllg** [comment]
Merged the Rmds in master.

**Pull request closed without merging**
