### PR TITLE
Port madrid usecases

### PR DESCRIPTION
**Pull request by pfistfl**
This ports the usecases from mlr-org/outreach
and adds a new usecase based on the titanic dataset

### CODE REVIEW

**Comment by jakob-r** [comment]
Is this ready for review?

**Comment by pfistfl** [comment]
Feel free to, build still fails due to datefeatures not beeing merged
@pkopper has a very similar PR for the mlr3book, he might wanna take over here.

**Comment by berndbischl** [comment]
please. disregard date features? the posts are already too complex anyway! delete the datefeatures from the dset and merge this. if you wanna talk about datefeatures, do in a separate post in a couple of maonths

**Comment by pfistfl** [comment]
Datefeatures is a different post, it was erroneously already merged.

**Comment by berndbischl** [comment]
ok so whats blocking here then?

**Comment by pat-s** [comment]
@pfistfl Just FYI: Your automatic line-break thing at 80 chrs is still happening.

**Pull request merged**
