### PR TITLE
mlr3 basics om iris

### PR DESCRIPTION
**Pull request by berndbischl**
Patrick, @pat-s please merge this in ASAP. and iterate over it for some minutes, please.

Comments:
- Please lets not discuss super tiny details here so much
- Add some few(!!) lines if you want to, but keep it a) super basic and simple b) not too much redundancy with the book
- the benchmark could maybe use 1-2 extra comments / lines?

thx!

### CODE REVIEW

**Comment by berndbischl** [comment]
uh, and the layout of some tables is not so great if they have large width, at least under local rendering. maybe you can do some magic here, please dont if this would take more than a few secs

**Comment by pfistfl** [comment]
Added via # 10

**Comment by pat-s** [comment]
I'll go over it again for a few minutes.

Just some things I saw on the first iteration:

- Please respect the coding style for such docs:
  - One sentence per line
  - No unnecessary blank lines
- There should be no need for `options(width = 400)`.
  If there is, we should at least drop a small explanation for readers.

Maybe the formatting stuff bugs a bit but if we enforce this for everyone, core people should also do it :)

**Comment by berndbischl** [comment]
> * Please respect the coding style for such docs

i will try, but now please help the boss to clean it up. he had to write it during the night and didnt want to in the first place :)


> * There should be no need for `options(width = 400)`.

i agree. but under local rendering with rmarkdown::render and then inspecting the html in chrome is really needed that?

**Comment by pat-s** [comment]
> i agree. but under local rendering with rmarkdown::render and then inspecting the html in chrome is really needed that?

I don't see a problem in the preview without that line.

**Pull request closed without merging**
